apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-depl
spec:
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: dockeridohyeah/cicd-dev:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
